### ISSUE TITLE
Using openssl doesn't work on a Mac, and is overkill on Linux

### ISSUE THREAD

**Issue by juliangilbey** [tesseract-ocr/tesstrain#85] opened 2019-09-03 11:14 UTC
Hi!  Thanks for this training example; it's really helpful!

I found that the Makefile line which sorts the list of training examples breaks on a Mac, presumably because it doesn't have named pipes.  But it is also somewhat of an overkill: sort -R --random-source only reads in 16 bytes from the random source to initialise the sorting, so sort -R is probably adequate here.  shuf reads in much more randomness than this, using the random-source for every step of the permutation, but it will fail on a Mac as the shuf command doesn't exist there.

Best wishes,

Julian

**Comment by stweil** [comment] 2019-09-03 13:50
Maybe I should reactivate my Python script to sort and shuffle the data. Obviously that would not only be much faster but also improve the portability. @wrznr, what do you think?

**Comment by kba** [comment] 2019-09-03 14:10
> that would not only be much faster but also improve the portability.

+1

**Comment by stweil** [comment] 2019-09-03 14:24
@juliangilbey, did you see [my report](https://github.com/tesseract-ocr/tesstrain/wiki/GT4HistOCR) in the Wiki? Maybe it also helps. And of course you are invited to share your results there, too.

**Comment by juliangilbey** [comment] 2019-09-03 16:52
Thanks - that's a nice report!

I wouldn't go to the effort of using python; I'd just replace

```
find $(GROUND_TRUTH_DIR) -name '*.lstmf' | sort | \
	  sort -R --random-source=<(openssl enc -aes-256-ctr -pass pass:"$(RANDOM_SEED)" -nosalt </dev/zero 2>/dev/null) > "$@"
```

(and I just noticed: there's an extra unnecessary `sort` in that pipeline!) with

```
find $(GROUND_TRUTH_DIR) -name '*.lstmf' | sort -R > "$@"
```

The only difference between this and the original version is that sort -R reads from /dev/urandom if it can, and if not, it does something else reasonably intelligent.  The original version uses the --random-source to get a 16-byte seed, and then uses some form of md5 hashing to generate later randomness.  So it will still be at least as good as the Python version.  (And MacOS supports sort -R.)

Best wishes,

Julian

**Comment by juliangilbey** [comment] 2019-09-03 16:54
Just a quick clarification: sort -R reads *its seed* from /dev/urandom if it can, and if not, it does something else reasonably intelligent to get a random seed.

**Comment by stweil** [comment] 2019-09-03 17:37
We want reproducible training results. Therefore we can only use pseudo random sequences. Using `/dev/urandom` is therefore not possible.

**Comment by juliangilbey** [comment] 2019-09-03 18:54
Ah, I missed that!

If all you then want is a reproducible result, you could have a 16+ byte file called seed.txt (eg "this is the reproducible seed file; do not modify"), and call --random-source=seed.txt.  That would work without the hassle of calling openssl or python.  You could even use one of the files already present for that, but its content might change at some point.

Best wishes,

Julian

**Comment by stweil** [comment] 2019-09-03 19:17
Does that work for Linux, too? I had a similar solution before, but with less than 16 bytes because I did not know that.

**Comment by juliangilbey** [comment] 2019-09-03 21:49
I would assume so, as both MacOS and Linux use GNU sort (from coreutils) as their implementation of /usr/bin/sort.

**Comment by wrznr** [comment] 2019-09-04 07:41
I am pretty sure that the BSD version of coreutils (which is the default on MacOS) does not offer `-R`.

**Comment by wrznr** [comment] 2019-09-04 07:48
After a little research, I fear that we have to go with Python if we want to be portable. `shuf` and `sort -R` are not available on MacOS (you have to install `coreutils` via brew or macports). Python is always present. I think the PR proposed by @stweil is sufficient.

**Comment by juliangilbey** [comment] 2019-09-04 08:38
I think that it may depend on what version of MacOS you are running; macOS Mojave (macOS 10.14) allows sort -R --random-source, and that's the BSD version of sort.  (I've just checked that on a fresh install of macOS, without brew or macports.)  Of course, the Python solution works too, but it assumes that python3 is installed, which it is not by default on a Mac :-(

**Comment by wrznr** [comment] 2019-09-04 08:43
If we are talking about portability, we should consider MacOS versions which are still officially supported. Concerning Python3, cf. https://github.com/tesseract-ocr/tesstrain/pull/86#discussion_r320618926

**Comment by stweil** [comment] 2019-09-04 10:24
@juliangilbey, Python 3 is required anyway for generating the line boxes, so that is not a new dependency.

**Comment by juliangilbey** [comment] 2019-09-04 12:12
True, true!

**Comment by stweil** [comment] 2019-09-04 12:46
PR #86 is merged now, so this issue should be fixed.

**Closed** 2019-09-26 13:27 UTC
Labels: bug, question
