### ISSUE TITLE
Unable to successfully process 'make leptonica tesseract'

### ISSUE THREAD

**Issue by sawankumar94** [tesseract-ocr/tesstrain#183] opened 2020-08-11 16:56 UTC

**Comment by sawankumar94** [comment] 2020-08-12 21:02
Hi,
I cloned 'https://github.com/tesseract-ocr/tesstrain.git' at one of directory in desktop.  I am using Ubuntu 20.04. I removed previously installed tesseract-ocr. I installed following libraries:
g++ , autoconf,  automake,  libtool, pkg-config, libpng-dev, libjpeg8-dev, libtiff5-dev, zlib1g-dev, libicu-dev, libpango1.0-dev, libcairo2-dev, libleptonica-dev, ca-certificates
from https://tesseract-ocr.github.io/tessdoc/Compiling and https://tesseract-ocr.github.io/tessdoc/Compiling-%E2%80%93-GitInstallation urls.

I tried doing 'make leptonica tesseract' on command line within 'tesstrain' directory. I have been getting this error 
make: ** [Makefile : 325: tesseract.built] Error 2 for long.

Please help.

Regards,
Sawan

**Comment by wrznr** [comment] 2020-08-13 13:06
Given the information you provide, we cannot help because we cannot identify the problem. At least, please provide the complete error message. Please, also consider to test whether your Tesseract installation actually works before you work with tesstrain.

**Comment by sawankumar94** [comment] 2020-08-13 13:54
Hi, 

Thank you for your response . I am attaching two screenshots where  i have highlighted error messages too. 
![Screenshot from 2020-08-13 19-14-53](https://user-images.githubusercontent.com/12645695/90142944-9ef85b80-dd9a-11ea-9bfa-ba4662dbed0f.png)
![Screenshot from 2020-08-13 19-23-38](https://user-images.githubusercontent.com/12645695/90142950-a0c21f00-dd9a-11ea-9368-bce4bcc4444f.png)

**Comment by wrznr** [comment] 2020-08-13 14:24
This looks like a linking error. Very strange. I fear that you will have to redo the installation procedure from scratch and provide the complete command line output as a text file.

@stweil Have you ever encountered such linking errors when building tesseract/tesstrain?

**Comment by rambalachandran** [comment] 2020-08-28 07:02
I'm having a similar issue when I try to run
````
make leptonica tesseract
````
This fails in the Makefile line 328 when trying to build tesseract
```
tesseract.built: tesseract-$(TESSERACT_VERSION)
	cd $< && \
		sh autogen.sh && \
		PKG_CONFIG_PATH="$(LOCAL)/lib/pkgconfig" \
			./configure --prefix=$(LOCAL) && \
		LDFLAGS="-L$(LOCAL)/lib"\
			make -j$(CORES) install training-install && \
		date > "$@"
```
I have attached the entire stdout and stderr that I got when running the command
[tesstrain_std.txt](https://github.com/tesseract-ocr/tesstrain/files/5140566/tesstrain_std.txt)

**Comment by wrznr** [comment] 2020-09-02 07:08
@rambalachandran Do you encounter the same problem if you build tesseract **outside** of `tesstrain`?

@stweil Do the Tesseract versions shipping with Linux distros contain the training tools? I.e. could installing leptonica and Tesseract via the distro and skipping `make leptonica tesseract` circumvent the linking errors described above?

**Comment by abandonware-magazines** [comment] 2020-09-05 11:22
I'm seeing the same issue.
Attaching the build log: [log.txt](https://github.com/tesseract-ocr/tesstrain/files/5177939/log.txt)

It ends with:
```console
Making all in unittest
make[3]: Entering directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0/unittest'
mkdir -p tmp
make[3]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0/unittest'
make[2]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0'
make[1]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0'
Makefile:328: recipe for target 'tesseract.built' failed
make: *** [tesseract.built] Error 2
```

If I cd into the tesseract folder and try to build from there, I don't see the error:
```console
$ cd tesseract-4.1.0/
$ ./autogen.sh
$ ./configure
$ make
```

Output:
```console
# ...
Making all in unittest
make[2]: Entering directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0/unittest'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0/unittest'
make[1]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0'
```


Another thing to note is the comment [here](https://tesseract-ocr.github.io/tessdoc/Compiling-%E2%80%93-GitInstallation) about `autoreconf -i`. However I tried to edit the makefile and add this additional command and it does not seem to resolve the issue:
```makefile
tesseract.built: tesseract-$(TESSERACT_VERSION)
	cd $< && \
		sh autogen.sh && \
		autoreconf -i && \
		PKG_CONFIG_PATH="$(LOCAL)/lib/pkgconfig" \
			./configure --prefix=$(LOCAL) && \
		LDFLAGS="-L$(LOCAL)/lib"\
			make -j$(CORES) install training-install && \
		date > "$@"
```

**Comment by abandonware-magazines** [comment] 2020-09-05 13:48
I had the same issue:
```
Making all in unittest
make[3]: Entering directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0/unittest'
mkdir -p tmp
make[3]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0/unittest'
make[2]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0'
make[1]: Leaving directory '/home/owner/Workspace/tesstrain/tesseract-4.1.0'
Makefile:328: recipe for target 'tesseract.built' failed
make: *** [tesseract.built] Error 2
```

I was able to resolve it by removing `-j$(CORES)` from the makefile command:
```console
$ git diff Makefile
diff --git a/Makefile b/Makefile
index dd440a4..3d225cb 100644
--- a/Makefile
+++ b/Makefile
@@ -330,7 +330,7 @@ tesseract.built: tesseract-$(TESSERACT_VERSION)
                PKG_CONFIG_PATH="$(LOCAL)/lib/pkgconfig" \
                        ./configure --prefix=$(LOCAL) && \
                LDFLAGS="-L$(LOCAL)/lib"\
-                       make -j$(CORES) install training-install && \
+                       make install training-install && \
                date > "$@"
```

**Comment by rambalachandran** [comment] 2020-09-08 04:50
@wrznr yes I can install tesseract separately if needed. The problem is in the makefile which is trying to install the tesseract version that is hosted by tesstrain. It needs to be fixed for this repository to be used by many people.

**Comment by wrznr** [comment] 2020-09-08 06:05
That is interesting.

@stweil @kba Could you please confirm this defective behavior? Does this indicate a dependency in the build process of Tesseract which is not correctly resolved by the parallelization mechanism of make?

**Comment by rambalachandran** [comment] 2020-09-08 06:25
I can also confirm that I followed @abandonware-magazines  and removing -j$(CORES) fixed the makefile bug

**Comment by stweil** [comment] 2020-09-08 06:29
Confirmed. And yes, that's a bug in the Makefiles of Tesseract 4.1.0 (and also 4.1.1). `make leptonica tesseract CORES=1` helps to work around that bug.

**Comment by rambalachandran** [comment] 2020-09-08 13:00
Its best if you can change the README.md to help people savetime from this bug

**Comment by stweil** [comment] 2020-09-08 13:08
It's even better to fix it, so people don't get a bug. I am already working on a fix.

**Comment by stweil** [comment] 2020-09-08 13:34
Pull request #193 fixes this bug and updates the software versions.

**Comment by stweil** [comment] 2020-09-08 13:44
The fix is merged now, so this issue can be closed. Please report if there remains a problem.

**Closed by stweil** 2020-09-08 13:44 UTC
